[build]
  command = "npm run build"
  publish = "."

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/sw.js"

  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/config.local.js"

  [headers.values]
    Cache-Control = "no-cache"
