name: warsaw_skate_app
description: Cross-platform Flutter prototype for inline skating routes in Warsaw.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  http: ^1.6.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
