export const WORDS = [
  {
    id: "dom-czesc",
    polish: "cześć",
    russian: "привет",
    topic: "Знакомство",
    level: "A1",
    example: "Cześć, miło cię widzieć.",
  },
  {
    id: "dom-dziekuje",
    polish: "dziękuję",
    russian: "спасибо",
    topic: "Знакомство",
    level: "A1",
    example: "Dziękuję za pomoc.",
  },
  {
    id: "dom-prosze",
    polish: "proszę",
    russian: "пожалуйста",
    topic: "Знакомство",
    level: "A1",
    example: "Proszę, usiądź tutaj.",
  },
  {
    id: "kawiarnia-kawa",
    polish: "kawa",
    russian: "кофе",
    topic: "Кафе",
    level: "A1",
    example: "Poproszę dużą kawę.",
  },
  {
    id: "kawiarnia-herbata",
    polish: "herbata",
    russian: "чай",
    topic: "Кафе",
    level: "A1",
    example: "Lubię zieloną herbatę.",
  },
  {
    id: "zakupy-sklep",
    polish: "sklep",
    russian: "магазин",
    topic: "Покупки",
    level: "A1",
    example: "Ten sklep jest blisko domu.",
  },
  {
    id: "zakupy-cena",
    polish: "cena",
    russian: "цена",
    topic: "Покупки",
    level: "A1",
    example: "Jaka jest cena tej książki?",
  },
  {
    id: "miasto-droga",
    polish: "droga",
    russian: "дорога",
    topic: "Город",
    level: "A1",
    example: "To jest długa droga do szkoły.",
  },
  {
    id: "miasto-dworzec",
    polish: "dworzec",
    russian: "вокзал",
    topic: "Город",
    level: "A1",
    example: "Dworzec jest po lewej stronie.",
  },
  {
    id: "codzienne-rano",
    polish: "rano",
    russian: "утром",
    topic: "Быт",
    level: "A1",
    example: "Rano piję kawę i czytam.",
  },
  {
    id: "codzienne-wieczor",
    polish: "wieczór",
    russian: "вечер",
    topic: "Быт",
    level: "A1",
    example: "Wieczór spędzam z rodziną.",
  },
  {
    id: "czas-dzisiaj",
    polish: "dzisiaj",
    russian: "сегодня",
    topic: "Время",
    level: "A1",
    example: "Dzisiaj mam lekcję polskiego.",
  },
];
